name: AWS Deployment with EKS & ECR & IAM

on:
  workflow_dispatch:

jobs:
  AWS-IAM-Configuration:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v3
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1 

     - name: Test AWS CLI
       run: aws sts get-caller-identity

     - name: Login to Amazon ECR
       run: |
         aws ecr get-login-password --region ap-south-1 | \
         docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

