name: AWS CLI Access with GitHub Work Flow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v3
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1  # Or use ${{ secrets.AWS_REGION }} if you stored it as a secret

     - name: Test AWS CLI
       run: aws sts get-caller-identity

  create-ec2-instance:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-00e3c023f0084cbfb \
            --instance-type t2.micro \
            --key-name AWS-Jenkins \
            --security-group-ids sg-070c369ac59b7efa0 \
            --count 1 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyInstance}]'
            
